### ISSUE TITLE
Vite support

### ISSUE THREAD

**Issue by philippkuehn** [holtwick/zeed-dom#1]
I finally try to move to zeed-dom this to tiptap because of [this issue](https://github.com/ueberdosis/tiptap/issues/2148) with hostic-dom 😅 
but an error is thrown when using in out vite setup.

<img width="924" alt="XUfSEX6LOu" src="https://user-images.githubusercontent.com/2500670/140896384-18251453-7913-4137-807b-06c2e82d42a2.png">

Not sure what’s wrong here. I created a reproducable demo:
https://stackblitz.com/edit/vite-bjcq7x?file=main.js

**Comment by holtwick** [comment]
Thanks @philippkuehn  I'll take a look

**Comment by holtwick** [comment]
I switched to tsup as a builder and made a typical copy and paste error while taking the boilerplate from another project :D Think it should work now. Happy you are using zeed-dom for TipTap now. Let me know, if run into other issues.

**Comment by philippkuehn** [comment]
Thanks! Works great so far. Unfortunarely there is still [this issue](https://github.com/ueberdosis/tiptap/issues/2148) with zeed-dom. I think @jcarvalho will create an issue with some more details here.
