### ISSUE TITLE
`he` is embedded instead of part of the dependencies

### ISSUE THREAD

**Issue by spaceemotion** [holtwick/zeed-dom#11]
Hi there! 

I stumbled upon this package due to tip-tap using it for its HTML parsing. While it works great for other use cases in my app, i noticed that the `he` package has been embedded as per https://github.com/holtwick/zeed-dom/commit/2079834d41704fa327f74d2376bdeb407c9a98bb.

Initially requested by https://github.com/holtwick/zeed-dom/issues/3 the `he` package already was a bit outdated when it was added. `zeed-dom` is the only package using `he` (even when it's embedded) while all other packages are using the `entities` package instead (lots more downloads and active development too).

A quick glance at [the benchmarks on `entities`' own README](https://github.com/fb55/entities#performance) shows `he` being quite slow compared to them, and according to bundlephobia, `he` is also a bit larger in size.

Is there a reason for going with a) an embedded version of the package and b) not with a different one instead?

Thanks in advance!

**Comment by holtwick** [comment]
That's a great hint. I don't remember the reason why I used and embedded `he` package. I'll take a look at the `entities` package and might use it. Just give me some days ;)
