### ISSUE TITLE
zeed dom is collecting all JSX elements it ever used in `USED_JSX`

### ISSUE THREAD

**Issue by floriankrueger** [holtwick/zeed-dom#2]
While digging into [this issue](https://github.com/ueberdosis/tiptap/issues/2148) with tiptap, my colleague @jcarvalho and I found the global variable `USED_JSX` to be the issue. Even serializing a simple document to HTML in a loop would quickly become slower and slower until it takes over a second to finish.

Memory was not an issue in our tests since the contents of `USED_JSX` where just the same elements over and over again so node itself could easily optimize that.

[tiptap issue #2148](https://github.com/ueberdosis/tiptap/issues/2148) lists an example on how to make this happen. Would be great if you could give an estimate on how easily this might be fixable. I tried switching it from a global var to a parameter yesterday but there are so many points where I needed to pass the parameter to, and some of them were getters or setters, so that wasn't achievable.

**Comment by holtwick** [comment]
Hi @floriankrueger I'll take a look. Thanks for investigating.

**Comment by holtwick** [comment]
I made a quick change, to improve the speed of the `USED_JSX` part. I'll further investigate, if it is required in that form at all or if it can be replaced by something smarter and more consistent. I'll keep this bug open until the evaluation finished. Thanks.

**Comment by floriankrueger** [comment]
Thank you for the intermediate fix! It'll improve the linear search a lot which should solve the reason for the performance issues that we were experiencing.

One concern remains even after the fix: Renders of previous documents are influencing upcoming documents. So the `true` returned by the check `if (USED_JSX[c] …` is incorrect at best and a minor security issue at worst (given that this is deciding on whether or now a certain string is escaped or rendered as html). Would you agree on that or am I misinterpreting something here?

**Comment by holtwick** [comment]
I removed the hack around `USED_JSX` altogether now. @floriankrueger , this should fix the concerns around global usage and also memory consumption. The code was old and made for a special purpose, now it should be up-to-date again. ;) 

https://github.com/holtwick/zeed-dom/commit/b88ae22216117d6b8ce39d5723593bfcb97bed64

**Comment by floriankrueger** [comment]
This is amazing, thank you so much for the time!

**Comment by holtwick** [comment]
No problem, thanks for pointing on the error and testing to make zeed-dom finally become a "Happy DOM" ;)
