### ISSUE TITLE
HTML entities are not being properly decoded

### ISSUE THREAD

**Issue by dodas** [holtwick/zeed-dom#3]
Seems like encoded html entities are not handled properly.
See this example: https://runkit.com/embed/9n1c04lodkqm
Providing the following html:
```html
<p>Let&#x27;s go</p>
```
I expect the following output when calling `parseHTML(html).textContent`:
```
Let's go
```
However, `zeed-dom` outputs the entities undecoded:
```
Let&#x27;s go
```

I can see there is a small list of encoded/decoded entites in [encoding.ts](https://github.com/holtwick/zeed-dom/blob/7a5ddd01f6ded86c37be9ff3f80ddaecf1fc76c0/src/encoding.ts), but all other entities are being ignored.
Seems like there used to be a check to optionally load `he` if available. I understand this could cause issues, however the current behavior is not ideal either. Can this be improved in any way?

Thanks!

**Comment by holtwick** [comment]
Thanks for good description of the problem. I'll look into it, this is indeed a bug.

**Comment by dodas** [comment]
Thanks for a swift fix!
Shouldn't `he` be now listed as `zeed-dom`'s `dependency` in `package.json`?

**Comment by holtwick** [comment]
Absolutely, here it is https://github.com/holtwick/zeed-dom/blob/master/package.json#L44

**Comment by dodas** [comment]
Ah, overlook that. Great!
